// doctorsData.js
const doctorsData = [
  {
    id: 1,
    name: 'Dr. John Doe',
    specialization: 'Cardiologist',
    phone: '+1 234 567 890',
    address: '123 Heart Avenue, NYC',
    hospital: 'Heart Care Hospital',
  },
  {
    id: 2,
    name: 'Dr. Jane Smith',
    specialization: 'Dermatologist',
    phone: '+1 987 654 321',
    address: '456 Skin Street, Boston',
    hospital: 'Skin Solutions Clinic',
  },
  {
    id: 3,
    name: 'Dr. Sarah Brown',
    specialization: 'Neurologist',
    phone: '+1 456 123 789',
    address: '789 Brain Lane, Chicago',
    hospital: 'Neuro Health Center',
  },
  {
    id: 4,
    name: 'Dr. Michael Green',
    specialization: 'Pediatrician',
    phone: '+1 321 654 987',
    address: '654 Child Way, Los Angeles',
    hospital: 'Children Care Hospital',
  },
  {
    id: 5,
    name: 'Dr. Alice White',
    specialization: 'General Practitioner',
    phone: '+1 555 123 456',
    address: '101 Main Street, Denver',
    hospital: 'Family Care Center',
  },
  {
    id: 6,
    name: 'Dr. Brian Black',
    specialization: 'General Practitioner',
    phone: '+1 555 987 654',
    address: '202 Oak Avenue, Miami',
    hospital: 'Wellness Clinic',
  },
  {
    id: 7,
    name: 'Dr. Emma Carter',
    specialization: 'Orthopedic',
    phone: '+1 234 567 891',
    address: '303 Bone Boulevard, Austin',
    hospital: 'Bone & Joint Health',
  },
  {
    id: 8,
    name: 'Dr. Daniel Lee',
    specialization: 'Orthopedic',
    phone: '+1 234 567 892',
    address: '404 Muscle Lane, Seattle',
    hospital: 'Orthopedic Solutions Center',
  },
  {
    id: 9,
    name: 'Dr. Lily King',
    specialization: 'Dentist',
    phone: '+1 234 567 893',
    address: '505 Smile Street, San Francisco',
    hospital: 'Bright Smiles Dental',
  },
  {
    id: 10,
    name: 'Dr. James Wilson',
    specialization: 'Dentist',
    phone: '+1 234 567 894',
    address: '606 Teeth Terrace, Dallas',
    hospital: 'Wilson Dental Clinic',
  },
  {
    id: 11,
    name: 'Dr. Olivia Taylor',
    specialization: 'Psychiatrist',
    phone: '+1 234 567 895',
    address: '707 Mind Lane, Portland',
    hospital: 'Mental Health Clinic',
  },
  {
    id: 12,
    name: 'Dr. Richard Davis',
    specialization: 'Psychiatrist',
    phone: '+1 234 567 896',
    address: '808 Thought Way, Phoenix',
    hospital: 'Davis Mental Health Center',
  },
];

export default doctorsData;
